### ISSUE TITLE
init.lua:389: module 'extractGram.lua' not found:  Thanks for your help!

### ISSUE THREAD

**Issue by tracy-Ming** [zhanghang1989/MSG-Net#2]
how to luarocks install extractGram?

init.lua:389: module 'extractGram.lua' not found:No LuaRocks module found for extractGram.lua
	no field package.preload['extractGram.lua']
	no file '/home/qxm/.luarocks/share/lua/5.1/extractGram/lua.lua'
	no file '/home/qxm/.luarocks/share/lua/5.1/extractGram/lua/init.lua'
	no file '/home/qxm/torch/install/share/lua/5.1/extractGram/lua.lua'
	no file '/home/qxm/torch/install/share/lua/5.1/extractGram/lua/init.lua'
	no file './extractGram/lua.lua'
	no file '/home/qxm/torch/install/share/luajit-2.1.0-beta1/extractGram/lua.lua'
	no file '/usr/local/share/lua/5.1/extractGram/lua.lua'
	no file '/usr/local/share/lua/5.1/extractGram/lua/init.lua'
	no file '/home/qxm/.luarocks/lib/lua/5.1/extractGram/lua.so'
	no file '/home/qxm/torch/install/lib/lua/5.1/extractGram/lua.so'
	no file '/home/qxm/torch/install/lib/extractGram/lua.so'
	no file './extractGram/lua.so'
	no file '/usr/local/lib/lua/5.1/extractGram/lua.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/qxm/.luarocks/lib/lua/5.1/extractGram.so'
	no file '/home/qxm/torch/install/lib/lua/5.1/extractGram.so'
	no file '/home/qxm/torch/install/lib/extractGram.so'
	no file './extractGram.so'
	no file '/usr/local/lib/lua/5.1/extractGram.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/home/qxm/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	test.lua:42: in function 'main'
	test.lua:102: in main chunk
	[C]: in function 'dofile'
	.../qxm/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50

**Comment by zhanghang1989** [comment]
Hi, please do 'git pull' and try again. Let me know if you still have troubles. Thanks!

**Comment by tracy-Ming** [comment]
Thanks for your help!
But, when i set "image_size =1024",
/torch/install/share/lua/5.1/cudnn/find.lua:469: No algorithms found that would fit in free GPU memory
What's wrong? The memory of my gpu is 3G，not enough?
Thank you !

**Comment by tracy-Ming** [comment]
Thanks!

**Comment by zhanghang1989** [comment]
No problem! I assume it is fixed.
