### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by pedrogarciafreitas** [zhanghang1989/MSG-Net#3]
I cloned repo and performed the following commands:

`git clone git@github.com:zhanghang1989/MSG-Net.git`
`cd MSG-Net/experiments`
`bash models/download_models.sh`
`th test.lua`

Test.lua did not work. I received the following error:

> /opt/torch/install/bin/luajit: /opt/torch/install/share/lua/5.1/trepl/init.lua:384: module 'texture' not found:No LuaRocks module found for texture
	no field package.preload['texture']
	no file '/home/pedro/.luarocks/share/lua/5.1/texture.lua'
	no file '/home/pedro/.luarocks/share/lua/5.1/texture/init.lua'
	no file '/opt/torch/install/share/lua/5.1/texture.lua'
	no file '/opt/torch/install/share/lua/5.1/texture/init.lua'
	no file './texture.lua'
	no file '/opt/torch/install/share/luajit-2.1.0-beta1/texture.lua'
	no file '/usr/local/share/lua/5.1/texture.lua'
	no file '/usr/local/share/lua/5.1/texture/init.lua'
	no file '/home/pedro/.luarocks/lib/lua/5.1/texture.so'
	no file '/opt/torch/install/lib/lua/5.1/texture.so'
	no file '/opt/torch/install/lib/texture.so'
	no file './texture.so'
	no file '/usr/local/lib/lua/5.1/texture.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/opt/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	test.lua:1: in main chunk
	[C]: in function 'dofile'
	/opt/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x004064d0

I tried to install the `texture' via

`luarocks install https://raw.githubusercontent.com/zhanghang1989/MSG-Net/master/texture-scm-1.rockspec`

It not worked. I received the following error:

> Using https://raw.githubusercontent.com/zhanghang1989/MSG-Net/master/texture-scm-1.rockspec... switching to 'build' mode
Cloning into 'MSG-Net'...
remote: Counting objects: 53, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 53 (delta 3), reused 49 (delta 3), pack-reused 0
Receiving objects: 100% (53/53), 5.95 MiB | 235.00 KiB/s, done.
Resolving deltas: 100% (3/3), done.
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /opt/torch/install
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "6.5") 
CMake Error at CMakeLists.txt:25 (INCLUDE):
  include could not find load file:
  /tmp/luarocks_texture-scm-1-5488/MSG-Net/cmake/select_compute_arch.cmake
CMake Error at CMakeLists.txt:27 (CUDA_SELECT_NVCC_ARCH_FLAGS):
  Unknown CMake command "CUDA_SELECT_NVCC_ARCH_FLAGS".
-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_texture-scm-1-5488/MSG-Net/build.luarocks/CMakeFiles/CMakeOutput.log".
See also "/tmp/luarocks_texture-scm-1-5488/MSG-Net/build.luarocks/CMakeFiles/CMakeError.log".
Error: Build error: Failed cmake.

But `/tmp/luarocks_texture-scm-1-5488/MSG-Net/build.luarocks/CMakeFiles/CMakeOutput.log` and `/tmp/luarocks_texture-scm-1-5488/MSG-Net/build.luarocks/CMakeFiles/CMakeError.log` do not exist.

I have installed Torch7, cudnn, cutorch and several other libs. Other learned scripts work in my system (e.g. https://github.com/manuelruder/artistic-videos, https://github.com/satoshiiizuka/siggraph2016_colorization/, and https://github.com/jcjohnson/neural-style).

I am using CentOS 7, cuda 8.0, and gcc 4.8.5.

**Comment by zhanghang1989** [comment]
Hi, I just updated the code. Please run the following command again:
`luarocks install https://raw.githubusercontent.com/zhanghang1989/MSG-Net/master/texture-scm-1.rockspec`
If you still get an error, please comment the following line:
https://github.com/zhanghang1989/MSG-Net/blob/master/CMakeLists.txt#L27

**Comment by pedrogarciafreitas** [comment]
It worked fined here. Thank you!
