### ISSUE TITLE
Question About Down-Sampling Residual Block

### ISSUE THREAD

**Issue by programath** [zhanghang1989/MSG-Net#4]
Hi, I'm a little confused about the architecture of the transformation network you described in your paper. I find that the k Residual Block is concatenated, and if one res-block down-samples the image by 2, then k res-block will down-samples by 2^k, which doesn't match the output size you describe in your paper.(It seems that whatever k is chosen, the image is down-sampled by 2)
Is there any part I missed? Thank you.

**Comment by zhanghang1989** [comment]
It is somehow misinterpreted. We always down sample the featuremaps 3 times (1/2^3). The k in the table 1 is just the number of residual blocks at each scale. In this experiments we let k=2.

**Comment by zhanghang1989** [comment]
I assume this issue is solved. Thanks!
