### ISSUE TITLE
Could not load model

### ISSUE THREAD

**Issue by jayavanth** [zhanghang1989/MSG-Net#6]
I get this when I run webcam.lua

`$ qlua webcam.lua `  
`Warning: Failed to load function from bytecode: binary string: bad header in precompiled chunkERROR: Could not load model from models/model_9styles.t7`
`You may need to download the pretrained models by running`

I have downloaded the model. It might be related to this issue: https://github.com/torch/torch7/issues/641. What lua version did you build the model with?

**Comment by zhanghang1989** [comment]
I used the default lua version that should be 5.1

**Comment by jayavanth** [comment]
Do I have to install this: https://github.com/DmitryUlyanov/texture_nets ? It's complaining about nn.InstanceNormalization

**Comment by jayavanth** [comment]
Fixed it by reinstalling torch with lua 5.1. Now, I'm getting this:
`
qlua: ./models/hang.lua:201: bad argument #1 to 'ipairs' (table expected, got string)
stack traceback:
	[C]: at 0x7fcd260dbf50
	[C]: in function 'ipairs'
	./models/hang.lua:201: in function 'createCNets'
	./extractGram.lua:37: in function 'exec'
	webcam.lua:47: in function 'main'
	webcam.lua:115: in main chunk
[1]    30586 segmentation fault (core dumped)  qlua webcam.lua
`
Am I supposed to pass the style_layer option?

**Comment by jayavanth** [comment]
It fixed itself ¯\\_(ツ)_/¯
